Fix bug in gradle
When there are multiple project dependencies with different gradle
settings, lack of an accurate version number for android.support lib
will cause error below:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-getui:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute
aapt
```